development:
  sessions:
    default:
      database: debatemate_development
      hosts:
        - localhost:27017
      options:
         pool_timeout: 0.5
  options:
    raise_not_found_error: false
test:
  sessions:
    default:
      database: debatemate_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
